Crypto-Config:

  # List of Symmetric Algorithms currently considered as Secure
  Symmetric-Encryption:
    Default-Algo: AES_CBC_256_PKCS5Padding
    Algorithms:
      - AES_CBC_128_PKCS5Padding
      - AES_CBC_128_PKCS7Padding  #Enabled For CSHARP/DOTNET
      - AES_CBC_192_PKCS5Padding
      - AES_CBC_256_PKCS5Padding
      - AES_GCM_128_NoPadding
      - AES_GCM_192_NoPadding
      - AES_GCM_256_NoPadding


  Interoperability:
    Languages:
      Python:
        Library-Provider: Default
        Symmetric:
          Default-Algo: AES_CBC_128_PKCS7Padding
          Encoding: UTF-8
          IV-Bytes: 16
          Resultant: BASE-64 #FIXED
      CSharp:
        Library-Provider: Microsoft
        Symmetric:
          Default-Algo: AES_CBC_128_PKCS7Padding
          Encoding: UTF-8
          IV-Bytes: 16
          Resultant: BASE-64 #FIXED
      DotNet:
        Library-Provider: Microsoft
        Symmetric:
          Default-Algo: AES_CBC_128_PKCS7Padding
          Encoding: UTF-8
          IV-Bytes: 16
          Resultant: BASE-64 #FIXED
