safencrypt:
  error:
    SAF-001: "Selected Algorithm [{0}] is not SET as SECURE in defined configuration"
    SAF-002: "Either the Key/IV/Associated Data used for encryption was different than provided for decryption"
    SAF-003: "Provided Key With Length [{0}] bytes is not compatible with selected algorithm [{1}], it should be exact [{2}] bytes long"
    SAF-004: "Selected Algorithm [{0}] is either incorrect OR not supported"
    SAF-005: "Associated Data can only be SET for algorithm AES_GCM"
    SAF-006: "Unable to load desired key with alias [{0}] from the keystore"
    SAF-007: "TAG is required while using algorithm AES_GCM for decryption"
    SAF-008: "TAG is not required while using algorithm [{0}] for decryption"
    SAF-009: "Provided Plaintext is should be Padded or must be at-least 16 bytes or its multiple (16,32,48,...)"
    SAF-010: "Either the Mode/Key/IV used for encryption was different than provided for decryption"
    SAF-011: "Usage of Algorithm [{0}] is insecure in client-server architecture"
    SAF-012: "Padding in Selected Algorithm [{0}] is incorrect"
    SAF-013: "Provided Ciphertext is should be Padded or must be at-least 16 bytes or its multiple (16,32,48,...)"
    SAF-014: "Provided IV With Length [{0}] bytes is not compatible with selected algorithm [{1}], it should be of [{2}] bytes"
