crypto-config:

  # List of Symmetric Algorithms currently considered as Secure
  symmetric-encryption:
    default-algo: AES_CBC_256_PKCS5Padding
    algorithms:
      - AES_CBC_128_PKCS5Padding
      - AES_CBC_128_PKCS7Padding  #Enabled For CSHARP/DOTNET
      - AES_CBC_256_PKCS7Padding  #Enabled For Python
      - AES_CBC_192_PKCS5Padding
      - AES_CBC_256_PKCS5Padding
      - AES_GCM_128_NoPadding
      - AES_GCM_192_NoPadding
      - AES_GCM_256_NoPadding



  #ONLY SUPPORTS AES_CBC and AES_GCM AS OF NOW
  interoperability:
    languages:
      python:
        library-Provider: Crypto
        symmetric:
          #          default-Algo: AES_CBC_256_PKCS7Padding
          default-Algo: AES_GCM_256_NoPadding
          iv-bytes: 12 #Recommended IV Length for AES_GCM
          tag-length: 16 #FIXED Default for Python
          resultant: BASE-64 #FIXED
      csharp:
        library-Provider: Microsoft
        symmetric:
          default-Algo: AES_CBC_128_PKCS7Padding
          iv-bytes: 16
          resultant: BASE-64 #FIXED
      DotNet:
        library-Provider: Microsoft
        symmetric:
          default-Algo: AES_CBC_128_PKCS7Padding
          iv-bytes: 16
          resultant: BASE-64 #FIXED



spring.profiles.include: 'keystore'

